// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pfSTqkNequKKnVXzrhC74aIpcgAW2PQ',
    appId: '1:13077254718:web:778a90282e51b6f260b76f',
    messagingSenderId: '13077254718',
    projectId: 'appdocbao-9d33b',
    authDomain: 'appdocbao-9d33b.firebaseapp.com',
    storageBucket: 'appdocbao-9d33b.appspot.com',
    measurementId: 'G-NX8DMD2JMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9gTRjWvQkab9wdKdFFSjMw2YyAiF3By0',
    appId: '1:13077254718:android:b8cb6e07477d9d3960b76f',
    messagingSenderId: '13077254718',
    projectId: 'appdocbao-9d33b',
    storageBucket: 'appdocbao-9d33b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5YrvT1pj8jPJNSHCNXNReIPwE6wz0F0',
    appId: '1:13077254718:ios:f3b98aa0b9a5cd6060b76f',
    messagingSenderId: '13077254718',
    projectId: 'appdocbao-9d33b',
    storageBucket: 'appdocbao-9d33b.appspot.com',
    iosBundleId: 'com.example.appDocbao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj5YrvT1pj8jPJNSHCNXNReIPwE6wz0F0',
    appId: '1:13077254718:ios:f3b98aa0b9a5cd6060b76f',
    messagingSenderId: '13077254718',
    projectId: 'appdocbao-9d33b',
    storageBucket: 'appdocbao-9d33b.appspot.com',
    iosBundleId: 'com.example.appDocbao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4pfSTqkNequKKnVXzrhC74aIpcgAW2PQ',
    appId: '1:13077254718:web:25bf3b85dceb480260b76f',
    messagingSenderId: '13077254718',
    projectId: 'appdocbao-9d33b',
    authDomain: 'appdocbao-9d33b.firebaseapp.com',
    storageBucket: 'appdocbao-9d33b.appspot.com',
    measurementId: 'G-Q7NK0XH02F',
  );
}
